behaviors:
  TetrisAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 100000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.98
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        encoding_size: 256
        learning_rate: 0.001
    behavioral_cloning: null
    framework: pytorch
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 512
    summary_freq: 10000
    threaded: true

environment_parameters:
  tetromino_types:
    curriculum:
      - name: "brain_dead"
        value: 1
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 2.0
      - name: "basic_placement"
        value: 2
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 5.0
      - name: "two_line_clear"
        value: 3
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "mid_stack"
        value: 4
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "flat_stack"
        value: 5
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "empty_board"
        value: 7
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 30.0

  board_height:
    curriculum:
      - name: "brain_dead"
        value: 8
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 2.0
      - name: "basic_placement"
        value: 10
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 5.0
      - name: "two_line_clear"
        value: 12
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "mid_stack"
        value: 14
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "flat_stack"
        value: 18
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "empty_board"
        value: 20
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 30.0

  hole_penalty_weight:
    curriculum:
      - name: "brain_dead"
        value: 0.1
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 2.0
      - name: "basic_placement"
        value: 0.1
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 5.0
      - name: "two_line_clear"
        value: 0.2
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "mid_stack"
        value: 0.3
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "flat_stack"
        value: 0.4
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "empty_board"
        value: 0.5
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 30.0

  board_preset:
    curriculum:
      - name: "brain_dead"
        value: 0
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 2.0
      - name: "basic_placement"
        value: 1
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 5.0
      - name: "two_line_clear"
        value: 2
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "mid_stack"
        value: 3
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "flat_stack"
        value: 4
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "empty_board"
        value: 6
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 30.0
