behaviors:
  TetrisAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 100000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.98
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        encoding_size: 256
        learning_rate: 0.001
    behavioral_cloning: null
    framework: pytorch
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 512
    summary_freq: 10000
    threaded: true

environment_parameters:
  # Tetromino progression - start simple, add complexity
  tetromino_types:
    curriculum:
      - name: "single_piece"
        value: 1 # Only I-pieces
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 2 # I and O pieces
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 3 # I, O, T pieces
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 5 # All except S and Z
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 7 # All tetrominoes
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Board height progression
  board_height:
    curriculum:
      - name: "single_piece"
        value: 8 # Very small for basic placement
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 10 # Small board
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 14 # Medium board
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 18 # Large board
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 20 # Full size
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Progressive hole penalty
  hole_penalty_weight:
    curriculum:
      - name: "single_piece"
        value: 0.02 # Very gentle - focus on basic placement
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 0.05 # Light penalty
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 0.1 # Moderate penalty
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 0.2 # Higher penalty
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 0.3 # Full penalty (reduced from 0.5)
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Board preset progression - CORRECTED to match C# switch cases
  board_preset:
    curriculum:
      - name: "single_piece"
        value: 1 # minimal_pre_config - Single I-piece placement
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 2 # basic_placement - Two-piece scenarios (I and O)
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 3 # guided_stacking - Multi-piece practice (I, O, T)
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 4 # structured_challenge - Multi-piece strategy
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 5 # complex_scenario - Advanced multi-level challenge
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Reward scaling to compensate for increased difficulty
  clearReward:
    curriculum:
      - name: "single_piece"
        value: 3.0 # Lower base reward for simple scenarios
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 4.0 # Slight increase
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 5.0 # Your current base
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 6.0 # Higher to compensate for difficulty
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 7.0 # Highest for full complexity
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Progressive T-spin enablement
  enable_t_spins:
    curriculum:
      - name: "single_piece"
        value: 0.0 # Disabled for early learning
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 0.0 # Still disabled
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 1.0 # Enable when T-pieces are introduced
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 1.0 # Keep enabled
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 1.0 # Keep enabled
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Perfect clear bonus scaling
  perfectClearBonus:
    curriculum:
      - name: "single_piece"
        value: 20.0 # Lower for simple scenarios
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 30.0
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 40.0
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 50.0 # Your current value
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 60.0 # Higher for full complexity
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0

  # Stagnation penalty factor - more forgiving early on
  stagnationPenaltyFactor:
    curriculum:
      - name: "single_piece"
        value: 0.0005 # Very light
        completion_criteria:
          min_lesson_length: 100000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 8.0
      - name: "basic_shapes"
        value: 0.0007
        completion_criteria:
          min_lesson_length: 150000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 12.0
      - name: "simple_shapes"
        value: 0.001 # Your current value
        completion_criteria:
          min_lesson_length: 200000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 18.0
      - name: "most_shapes"
        value: 0.0012
        completion_criteria:
          min_lesson_length: 250000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 25.0
      - name: "all_shapes"
        value: 0.0015 # Slightly more aggressive for full game
        completion_criteria:
          min_lesson_length: 300000
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 35.0
