behaviors:
  TetrisAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 347
      buffer_size: 27814
      learning_rate: 3.1567360682923474e-05
      beta: 0.007564234116635453
      epsilon: 0.15676244393181094
      lambd: 0.9559281042681499
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        encoding_size: 256
        learning_rate: 0.001
    behavioral_cloning:
    framework: pytorch
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 512
    summary_freq: 10000
    threaded: true

environment_parameters:
  tetromino_types:
    curriculum:
      - name: "single_piece"
        value: 1
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 2
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 3
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 5
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 7
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  board_height:
    curriculum:
      - name: "single_piece"
        value: 8
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 10
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 14
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 18
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 20
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  hole_penalty_weight:
    curriculum:
      - name: "single_piece"
        value: 0.02
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 0.05
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 0.1
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 0.2
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 0.3
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  board_preset:
    curriculum:
      - name: "single_piece"
        value: 1
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 2
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 3
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 4
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 5
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  clearReward:
    curriculum:
      - name: "single_piece"
        value: 3.0
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 4.0
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 5.0
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 6.0
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 7.0
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  enable_t_spins:
    curriculum:
      - name: "single_piece"
        value: 0.0
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 0.0
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 1.0
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 1.0
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 1.0
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  perfectClearBonus:
    curriculum:
      - name: "single_piece"
        value: 20.0
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 30.0
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 40.0
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 50.0
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 60.0
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  stagnationPenaltyFactor:
    curriculum:
      - name: "single_piece"
        value: 0.0005
        completion_criteria:
          min_lesson_length: 100
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "basic_shapes"
        value: 0.0007
        completion_criteria:
          min_lesson_length: 150
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "simple_shapes"
        value: 0.001
        completion_criteria:
          min_lesson_length: 200
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "most_shapes"
        value: 0.0012
        completion_criteria:
          min_lesson_length: 250
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0
      - name: "all_shapes"
        value: 0.0015
        completion_criteria:
          min_lesson_length: 300
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          threshold: 0

  clearReward: 5.0
  comboMultiplier: 0.5
  tetrisClearRewardMultiplier: 15.0
  tripleLineClearRewardMultiplier: 7.0
  doubleLineClearRewardMultiplier: 3.0
  perfectClearBonus: 50.0
  tSpinReward: 1.0
  iPieceGapFillBonus: 0.8
  deathPenalty: 2.0
  stagnationPenaltyFactor: 0.001
  stackHeightPenalty: 0.02
  holeCreationPenalty: 0.99979
  uselessRotationPenalty: 0.01
  idleActionPenalty: 0.001
  roughnessRewardMultiplier: 0.3
  roughnessPenaltyMultiplier: 0.01
  holeFillReward: 1.0
  wellRewardMultiplier: 0.2
  iPieceInWellBonus: 0.5
  maxWellRewardCap: 1.0
  accessibilityRewardMultiplier: 0.2
  accessibilityPenaltyMultiplier: 0.05
