---
default_settings:
behaviors:
  TetrisAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 468
      buffer_size: 100000
      learning_rate: 0.0002297549705702077
      beta: 0.009272627483945443
      epsilon: 0.2908023414194661
      lambd: 0.9718309466112697
      num_epoch: 7
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3 # Reduced from 4 to 3 layers for faster training
      vis_encode_type: simple
      memory:
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory:
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.3
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          memory:
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.001
        encoding_size: 256
    init_path:
    keep_checkpoints: 5
    checkpoint_interval: 5000
    max_steps: 50000
    time_horizon: 512
    summary_freq: 1000
    threaded: true
    self_play:
    behavioral_cloning:

env_settings:
  env_path: /Users/anandpatil/Documents/Projects/tetris-multi/Build/tetris.app
  env_args:
  base_port: 5005
  num_envs: 4 # Increased from 1 to 4 to speed up training
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

checkpoint_settings:
  run_id: tetris_training
  initialize_from:
  load_model: false
  resume: false
  force: true
  train_model: true
  inference: false
  results_dir: results

torch_settings:
  device:

debug: false

environment_parameters:
  tetromino_types:
    curriculum:
      - name: brain_dead
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 1
      - name: basic_placement
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5.0
        value: 2
      - name: intermediate_shapes
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 15.0
        value: 4
      - name: advanced_tetris
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 7

  board_height:
    curriculum:
      - name: brain_dead
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 8
      - name: basic_placement
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 10.0
        value: 10
      - name: intermediate_shapes
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 15.0
        value: 15
      - name: advanced_tetris
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 20

  hole_penalty_weight:
    curriculum:
      - name: brain_dead
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 0.1
      - name: basic_placement
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5.0
        value: 0.1
      - name: intermediate_shapes
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 15.0
        value: 0.3
      - name: advanced_tetris
        completion_criteria:
          measure: reward
          behavior: TetrisAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 0.5
  clearReward: 1.2905176545718522
  comboMultiplier: 1.9181344279379031
  perfectClearBonus: 1.835557540863932
  stagnationPenaltyFactor: 0.1717589864714183
  roughnessRewardMultiplier: 1.343980459523036
  roughnessPenaltyMultiplier: 0.0051742343892380305
  holeFillReward: 1.943680337719485
  holeCreationPenalty: 2.3958509116764763
  wellRewardMultiplier: 1.147604147410948
  iPieceInWellBonus: 0.14611423228964648
  stackHeightPenalty: 0.48666569294530604
  uselessRotationPenalty: 0.13600917410272195
  tSpinReward: 0.2512680798743616
  iPieceGapFillBonus: 0.7307297734288369
  accessibilityRewardMultiplier: 0.8042692784793886
  accessibilityPenaltyMultiplier: 1.5369930333302422
  deathPenalty: -4.23171392038166
  idleActionPenalty: -0.3284216246373971
  moveDownActionReward: 0.9657323620795467
  hardDropActionReward: 1.0440454471730878
  doubleLineClearRewardMultiplier: 1.086530372526832
  tripleLineClearRewardMultiplier: 1.7583412553366884
  tetrisClearRewardMultiplier: 3.8932452084189375
  maxWellRewardCap: 9.134961369191824
