default_settings: null
behaviors:
  TetrisAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 100000
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.3
      lambd: 0.98
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3 # Reduced from 4 to 3 layers for faster training
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.3
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.001
        encoding_size: 256
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 5000
    max_steps: 10000000
    time_horizon: 512
    summary_freq: 1000
    threaded: true
    self_play: null
    behavioral_cloning: null

env_settings:
  env_path: /Users/anandpatil/Documents/Projects/tetris-multi/Build/tetris.app
  env_args: null
  base_port: 5005
  num_envs: 4 # Increased from 1 to 4 to speed up training
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

checkpoint_settings:
  run_id: tetris_training
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: true
  inference: false
  results_dir: results

torch_settings:
  device: null

debug: false

environment_parameters:
  tetromino_types:
    curriculum:
      - name: "brain_dead"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 1
      - name: "basic_placement"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5.0
        value: 2
      - name: "intermediate_shapes"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 15.0
        value: 4
      - name: "advanced_tetris"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 7

  board_height:
    curriculum:
      - name: "brain_dead"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 8
      - name: "basic_placement"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 10.0
        value: 10
      - name: "intermediate_shapes"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 15.0
        value: 15
      - name: "advanced_tetris"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 20

  hole_penalty_weight:
    curriculum:
      - name: "brain_dead"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 0.1
      - name: "basic_placement"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5.0
        value: 0.1
      - name: "intermediate_shapes"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 15.0
        value: 0.3
      - name: "advanced_tetris"
        completion_criteria:
          measure: "reward"
          behavior: "TetrisAgent"
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 0.5
